### ISSUE TITLE
osx build failed to build on travis

### ISSUE THREAD

**Issue by jobovy** [conda-forge/galpy-feedstock#1]
The travis OSX build does not seem to have happened, so there's no mac osx conda package for galpy. Is this expected? The travis [request](https://travis-ci.org/conda-forge/galpy-feedstock/requests) says ``"Build config file is required via repository settings, but config is empty."``, yet there is a ``.travis.yml`` file in the feedstock.

**Comment by bsipocz** [comment]
@jobovy - I've force pushed back the latest commit, I think it just did the trick.

**Comment by jobovy** [comment]
Cool, thanks! That seems to have done the trick! (took a long time for travis to actually start the build it seems...)
